# This playbook configures the Wharehauora development server
---
- hosts: wharehauora
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/rbenv_vars.yml
  
  roles:
    - { role: 'centos-config', tags: 'centos' } 
    - { role: 'ansible-rbenv-role', tags: 'ruby' } 