- name: "Installing CentOS/7 dependencies: http-parser (package from the fedora repo)"
  yum:
    name: https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
    state: present

- name: Installing CentOS/7 dependencies (epel-release)
  yum: 
    name: epel-release
    state: latest

- name: Installing other CentOS/7 dependencies
  yum: pkg={{item}} state=installed
  with_items:
  - git-core 
  - zlib 
  - zlib-devel 
  - gcc-c++ 
  - patch 
  - readline 
  - readline-devel 
  - libyaml-devel 
  - openssl-devel 
  - make 
  - bzip2 
  - autoconf 
  - automake 
  - libtool 
  - bison 
  - curl 
  - sqlite-devel
  - postgresql-devel 
  - nodejs 
  - npm
  - postgresql-server 
  - postgresql-contrib